IF
	AttackedBy([ENEMY.UNDEAD],DEFAULT)
	Allegiance(LastAttackerOf(Myself),ENEMY)
	General(LastAttackerOf(Myself),UNDEAD)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ClearActions(LastAttackerOf(Myself))
		Continue()
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	OnCreation()
	!See(NearestEnemyOf(Myself))
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ApplySpellRES("dw#thinv",Myself)  // ??????????? (????????? ???????)
END

IF
	OnCreation()
	See(NearestEnemyOf(Myself))
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ApplySpellRES("dw#thinv",Myself)  // ??????????? (????????? ???????)
		SetGlobal("backstabplan","LOCALS",1)
		SetGlobal("backstabtimer","LOCALS",6)
END

IF
	OnCreation()
	See(NearestEnemyOf(Myself))
	Class(Myself,THIEF_ALL)
	StateCheck(Myself,STATE_INVISIBLE)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("backstabplan","LOCALS",1)
		SetGlobalTimer("backstabtimer","LOCALS",ONE_ROUND)
END

IF
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	Allegiance(Myself,ENEMY)
	!Detect(NearestEnemyOf(Myself))
	!Detect(Player1)
	!Detect(Player2)
	!Detect(Player3)
	!Detect(Player4)
	!Detect(Player5)
	!Detect(Player6)
THEN
	RESPONSE #100
		ApplySpellRES("dw#thinv",Myself)  // ??????????? (????????? ???????)
END

IF
	!Global("inafight","LOCALS",1)
	!Gender(Myself,SUMMONED)
	!Gender(Myself,IMPRISONED_SUMMONED)
	OR(7)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("inafight","LOCALS",1)
		SetGlobalTimer("stayontarget","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("seedefences","LOCALS",ONE_ROUND)
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	!Gender(Myself,SUMMONED)
	!Gender(Myself,IMPRISONED_SUMMONED)
	OR(7)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

IF
	!Global("inafight","LOCALS",1)
	OR(9)
		See(NearestEnemyOf(Myself))
		Heard([ANYONE],404)
		Heard([ANYONE],405)
		Heard([ANYONE],406)
		Heard([ANYONE],407)
		Heard([ANYONE],408)
		Heard([ANYONE],409)
		Heard([ANYONE],410)
		Heard([ANYONE],411)
THEN
	RESPONSE #100
		SetGlobal("inafight","LOCALS",1)
		SetGlobalTimer("stayontarget","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("seedefences","LOCALS",ONE_ROUND)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("rest","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("rtime","LOCALS",2000)
		SetGlobal("rest","LOCALS",1)
		Continue()
END

IF
	Global("rest","LOCALS",1)
	!GlobalTimerNotExpired("rtime","LOCALS")
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("rest","LOCALS",0)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
		Rest()
END

IF
	Allegiance(Myself,ENEMY)
	OR(12)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
		SpellCastOnMe([PC],0)
		SpellCastOnMe([FAMILIAR],0)
		SpellCastOnMe([ALLY],0)
		SpellCastOnMe([CONTROLLED],0)
		SpellCastOnMe([CHARMED],0)
	!GlobalTimerNotExpired("whatthe","LOCALS")
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("whatthe","LOCALS",TWO_ROUNDS)
		Continue()
END

IF
	!See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("seencloud","LOCALS")
	GlobalTimerNotExpired("whatthe","LOCALS")
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	OR(2)
		Heard([ANYONE],405)
		Heard([ANYONE],409)
	Range(LastHeardBy(Myself),20)
	!CheckStatGT(Myself,99,RESISTFIRE)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		RunAwayFrom(LastHeardBy(Myself),30)
END

IF
	Heard([ANYONE],408)
	Range(LastHeardBy(Myself),20)
	!CheckStatGT(Myself,99,RESISTACID)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		RunAwayFrom(LastHeardBy(Myself),30)
END

IF
	Heard([ANYONE],404)
	Range(LastHeardBy(Myself),20)
	!General(Myself,UNDEAD)
	!Race(Myself,RAKSHASA)
	!Race(Myself,DEMONIC)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		RunAwayFrom(LastHeardBy(Myself),30)
END

IF
	See(NearestEnemyOf(Myself))
	!Global("chasing","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("chasing","LOCALS",0)
		ClearActions(Myself)
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",1)
		Continue()
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player2)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",2)
		Continue()
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player3)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",3)
		Continue()
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player4)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",4)
		Continue()
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player5)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",5)
		Continue()
END

IF
	!GlobalTimerNotExpired("chasetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(Player6)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
		SetGlobal("chasePC","LOCALS",6)
		Continue()
END

IF
	Global("chasePC","LOCALS",1)
	StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	Global("chasePC","LOCALS",2)
	StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	Global("chasePC","LOCALS",3)
	StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	Global("chasePC","LOCALS",4)
	StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	Global("chasePC","LOCALS",5)
	StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	Global("chasePC","LOCALS",6)
	StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("chasePC","LOCALS",0)
		Continue()
END

IF
	CheckStatGT(Myself,19,LEVEL)
	!HasItem("dw#nohla",Myself)  // ????? ??????? ?????
	OR(2)
		GlobalGT("Chapter","GLOBAL",7)
		AmIInWatchersKeepPleaseIgnoreTheLackOfApostophe()
	!GlobalTimerNotExpired("HLAInitialize","LOCALS")
	OR(3)
		Class(Myself,FIGHTER_ALL)
		Class(Myself,RANGER_ALL)
		Class(Myself,PALADIN_ALL)
THEN
	RESPONSE #100
		SetGlobalTimer("HLAInitialize","LOCALS",1000)
		SetGlobal("FighterAbility","LOCALS",2)
		Continue()
END

IF
	HasItem("POTN34",Myself)  // ????? ????????????? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102237)  // ???? ????? ?????????? ??????
		UseItem("POTN34",Myself)  // ????? ????????????? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN35",Myself)  // ????? ?????????? ?? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102238)  // ???? ????? ??????????? ???????
		UseItem("POTN35",Myself)  // ????? ?????????? ?? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN21",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102239)  // ???? ????? ???????
		UseItem("POTN21",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN45",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102240)  // ???? ????? ???????
		UseItem("POTN45",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn34",Myself)  // ????? ????????????? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102241)  // ???? ????? ????????????? ?????
		UseItem("potn34",Myself)  // ????? ????????????? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn35",Myself)  // ????? ?????????? ?? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102242)  // ???? ????? ?????????? ?? ?????
		UseItem("potn35",Myself)  // ????? ?????????? ?? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn21",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102243)  // ???? ????? ???????
		UseItem("potn21",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn45",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	!CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102244)  // ???? ????? ???????
		UseItem("potn45",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_HARDINESS)  // SPCL907.SPL (?????????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),30)
	OR(2)
		!CheckStatGT(Myself,39,RESISTCRUSHING)
		!CheckStatGT(Myself,39,RESISTSLASHING)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (?????????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (?????? ???????? ?????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,5,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (?????? ???????? ?????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_SMITE)  // SPCL909.SPL (?????????????? ????)
	AreaType(OUTDOOR)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,5,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_SMITE)  // SPCL909.SPL (?????????????? ????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (??????????? ????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,3,SCRIPTINGSTATE4)
	!CheckStat(Myself,5,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (??????????? ????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(ROGUE_ASSASINATION)  // SPCL916.SPL (????????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,4,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,ROGUE_ASSASINATION)  // SPCL916.SPL (????????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_WHIRLWIND)  // SPCL900.SPL (???????? ?????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStatGT(Myself,3,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_WHIRLWIND)  // SPCL900.SPL (???????? ?????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(WARRIOR_POWER_ATTACK)  // SPCL906.SPL (??????? ?????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,2,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,WARRIOR_POWER_ATTACK)  // SPCL906.SPL (??????? ?????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalGT("FighterAbility","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,3,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (??????????? ????)
		IncrementGlobal("FighterAbility","LOCALS",-1)
	RESPONSE #200
		Continue()
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	See(NearestEnemyOf(Myself))
	GlobalGT("FighterAbility","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,5,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (?????? ???????? ?????)
		IncrementGlobal("FighterAbility","LOCALS",-1)
	RESPONSE #100
		Continue()
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	AreaType(OUTDOOR)
	See(NearestEnemyOf(Myself))
	GlobalGT("FighterAbility","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,5,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WARRIOR_SMITE)  // SPCL909.SPL (?????????????? ????)
		IncrementGlobal("FighterAbility","LOCALS",-1)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(BERSERKER_ENRAGE)  // SPCL321.SPL (??????)
	See(NearestEnemyOf(Myself))
	!CheckStat(Myself,1,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,BERSERKER_ENRAGE)  // SPCL321.SPL (??????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(BARBARIAN_RAGE)  // SPCL152.SPL (?????? ???????)
	See(NearestEnemyOf(Myself))
	!CheckStat(Myself,1,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,BARBARIAN_RAGE)  // SPCL152.SPL (?????? ???????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(KENSAI_KIA)  // SPCL144.SPL (???)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,2,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,KENSAI_KIA)  // SPCL144.SPL (???)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(ASSASSIN_POISON)  // SPCL423.SPL (??????????? ??????)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	!CheckStat(Myself,4,SCRIPTINGSTATE4)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,ASSASSIN_POISON)  // SPCL423.SPL (??????????? ??????)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HaveSpell(ARCHER_CALL_SHOT)  // SPCL121.SPL (?????????? ???????)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("calledshot","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		Spell(Myself,ARCHER_CALL_SHOT)  // SPCL121.SPL (?????????? ???????)
		SetGlobalTimer("calledshot","LOCALS",TWO_ROUNDS)
END

IF
	HasItem("POTN10",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
THEN
	RESPONSE #200
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102245)  // ???? ????? ???????????
		UseItem("POTN10",Myself)  // ????? ???????????
		Wait(1)
		SetGlobal("backstabplan","LOCALS",1)
		SetGlobalTimer("backstabtimer","LOCALS",ONE_ROUND)
	RESPONSE #100
		Continue()
END

IF
	HasItem("potn10",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
THEN
	RESPONSE #200
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102245)  // ???? ????? ???????????
		UseItem("potn10",Myself)  // ????? ???????????
		Wait(1)
		SetGlobal("backstabplan","LOCALS",1)
		SetGlobalTimer("backstabtimer","LOCALS",ONE_ROUND)
	RESPONSE #100
		Continue()
END

IF
	HasItem("POTN10",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102245)  // ???? ????? ???????????
		UseItem("POTN10",Myself)  // ????? ???????????
		SetGlobal("backstabplan","LOCALS",2)
END

IF
	HasItem("potn10",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	Class(Myself,THIEF_ALL)
	!StateCheck(Myself,STATE_INVISIBLE)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102245)  // ???? ????? ???????????
		UseItem("potn10",Myself)  // ????? ???????????
		SetGlobal("backstabplan","LOCALS",2)
END

IF
	GlobalGT("backstabplan","LOCALS",0)
	!HasItem("POTN10",Myself)  // ????? ???????????
	!HasItem("potn10",Myself)  // ????? ???????????
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobal("backstabplan","LOCALS",0)
END

IF
	See(NearestEnemyOf(Myself))
	Global("backstabplan","LOCALS",0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobal("backstabplan","LOCALS",1)
		SetGlobalTimer("backstabtimer","LOCALS",ONE_ROUND)
END

IF
	HasItem("POTN17",Myself)  // ??????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102246)  // ???? ????? ???????
		UseItem("POTN17",Myself)  // ??????? ????????
END

IF
	HasItem("potn17",Myself)  // ??????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102246)  // ???? ????? ???????
		UseItem("potn17",Myself)  // ??????? ????????
END

IF
	HasItem("POTN20",Myself)  // ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102247)  // ????????? ???????????
		UseItem("POTN20",Myself)  // ???????????
END

IF
	HasItem("potn20",Myself)  // ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102247)  // ????????? ???????????
		UseItem("potn20",Myself)  // ???????????
END

IF
	HasItem("POTN55",Myself)  // ????? ????????????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	HPPercentLT(Myself,50)
	!General(Myself,UNDEAD)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102248)  // ???? ????? ????????????? ???????
		UseItem("POTN55",Myself)  // ????? ????????????? ???????
END

IF
	HasItem("potn55",Myself)  // ????? ????????????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	HPPercentLT(Myself,50)
	!General(Myself,UNDEAD)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102248)  // ???? ????? ????????????? ???????
		UseItem("potn55",Myself)  // ????? ????????????? ???????
END

IF
	HasItem("POTN52",Myself)  // ????? ??????????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	!GlobalGT("Chapter","GLOBAL",7)
	HPPercentLT(Myself,50)
	!General(Myself,UNDEAD)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102249)  // ???? ????? ??????????? ???????
		UseItem("POTN52",Myself)  // ????? ??????????? ???????
END

IF
	HasItem("potn52",Myself)  // ????? ??????????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	!GlobalGT("Chapter","GLOBAL",7)
	HPPercentLT(Myself,50)
	!General(Myself,UNDEAD)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102249)  // ???? ????? ??????????? ???????
		UseItem("potn52",Myself)  // ????? ??????????? ???????
END

IF
	HasItem("POTN14",Myself)  // ????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_HASTED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102250)  // ???? ????? ????????
		UseItem("POTN14",Myself)  // ????? ????????
END

IF
	HasItem("potn14",Myself)  // ????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_HASTED)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102250)  // ???? ????? ????????
		UseItem("potn14",Myself)  // ????? ????????
END

IF
	HasItem("POTN07",Myself)  // ????? ???? ?????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,24,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102251)  // ???? ????? ???? ?????????? ????????
		UseItem("POTN07",Myself)  // ????? ???? ?????????? ????????
END

IF
	HasItem("potn07",Myself)  // ????? ???? ?????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,24,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102251)  // ???? ????? ???? ?????????? ????????
		UseItem("potn07",Myself)  // ????? ???? ?????????? ????????
END

IF
	HasItem("POTN06",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,23,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102252)  // ???? ????? ???? ????????? ????????
		UseItem("POTN06",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("potn06",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,23,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102252)  // ???? ????? ???? ????????? ????????
		UseItem("potn06",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("POTN05",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,22,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102253)  // ???? ????? ???? ????????? ????????
		UseItem("POTN05",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("potn05",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,22,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102253)  // ???? ????? ???? ????????? ????????
		UseItem("potn05",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("POTN04",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,21,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102254)  // ???? ????? ???? ????????? ????????
		UseItem("POTN04",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("potn04",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,21,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102254)  // ???? ????? ???? ????????? ????????
		UseItem("potn04",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("POTN12",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,20,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102255)  // ???? ????? ???? ????????? ????????
		UseItem("POTN12",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("potn12",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,20,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102255)  // ???? ????? ???? ????????? ????????
		UseItem("potn12",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("POTN03",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,19,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102256)  // ???? ????? ???? ????????? ????????
		UseItem("POTN03",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("potn03",Myself)  // ????? ???? ????????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,19,STR)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102256)  // ???? ????? ???? ????????? ????????
		UseItem("potn03",Myself)  // ????? ???? ????????? ????????
END

IF
	HasItem("POTN34",Myself)  // ????? ????????????? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102257)  // ???? ????? ????????????? ?????
		UseItem("POTN34",Myself)  // ????? ????????????? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN35",Myself)  // ????? ?????????? ?? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102258)  // ???? ????? ?????????? ?? ?????
		UseItem("POTN35",Myself)  // ????? ?????????? ?? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN21",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102243)  // ???? ????? ???????
		UseItem("POTN21",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN45",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102244)  // ???? ????? ???????
		UseItem("POTN45",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn34",Myself)  // ????? ????????????? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102257)  // ???? ????? ????????????? ?????
		UseItem("potn34",Myself)  // ????? ????????????? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn35",Myself)  // ????? ?????????? ?? ?????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102258)  // ???? ????? ?????????? ?? ?????
		UseItem("potn35",Myself)  // ????? ?????????? ?? ?????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn21",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102243)  // ???? ????? ???????
		UseItem("potn21",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("potn45",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("takendefence","LOCALS",1)
	CheckStatGT(Myself,13,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102244)  // ???? ????? ???????
		UseItem("potn45",Myself)  // ????? ???????
		SetGlobal("takendefence","LOCALS",1)
END

IF
	HasItem("POTN41",Myself)  // ????? ??????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Global("heroptn","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102259)  // ???? ????? ??????????
		UseItem("POTN41",Myself)  // ????? ??????????
		SetGlobal("heroptn","LOCALS",1)
END

IF
	HasItem("potn41",Myself)  // ????? ??????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Global("heroptn","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102259)  // ???? ????? ??????????
		UseItem("potn41",Myself)  // ????? ??????????
		SetGlobal("heroptn","LOCALS",1)
END

IF
	HasItem("POTN09",Myself)  // ????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Global("heroptn","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102260)  // ???? ????? ????????
		UseItem("POTN09",Myself)  // ????? ????????
		SetGlobal("heroptn","LOCALS",1)
END

IF
	HasItem("potn09",Myself)  // ????? ????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Global("heroptn","LOCALS",0)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102260)  // ???? ????? ????????
		UseItem("potn09",Myself)  // ????? ????????
		SetGlobal("heroptn","LOCALS",1)
END

IF
	HasItem("POTN24",Myself)  // ????? ??????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatGT(Myself,0,ARMORCLASS)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102261)  // ???? ????? ??????
		UseItem("POTN24",Myself)  // ????? ??????
END

IF
	HasItem("potn24",Myself)  // ????? ??????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatGT(Myself,0,ARMORCLASS)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102261)  // ???? ????? ??????
		UseItem("potn24",Myself)  // ????? ??????
END

IF
	HasItem("POTN28",Myself)  // ????? ?????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,15,CON)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102262)  // ???? ????? ?????????
		UseItem("POTN28",Myself)  // ????? ?????????
END

IF
	HasItem("potn28",Myself)  // ????? ?????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	CheckStatLT(Myself,15,CON)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102262)  // ???? ????? ?????????
		UseItem("potn28",Myself)  // ????? ?????????
END

IF
	HasItem("POTN42",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102263)  // ???? ????? ???????????
		UseItem("POTN42",Myself)  // ????? ???????????
END

IF
	HasItem("potn42",Myself)  // ????? ???????????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102263)  // ???? ????? ???????????
		UseItem("potn42",Myself)  // ????? ???????????
END

IF
	HasItem("POTN08",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102246)  // ???? ????? ???????
		UseItem("POTN08",Myself)  // ????? ???????
END

IF
	HasItem("potn08",Myself)  // ????? ???????
	!GlobalTimerNotExpired("castspell","LOCALS")
	!General(Myself,ANIMAL)
	!General(Myself,MONSTER)
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,102246)  // ???? ????? ???????
		UseItem("potn08",Myself)  // ????? ???????
END

IF
	OR(2)
		Heard([ANYONE],405)
		Heard([ANYONE],409)
	Range(LastHeardBy(Myself),20)
	!CheckStatGT(Myself,99,RESISTFIRE)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	See([PC])
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		MoveToObject([PC])
END

IF
	Heard([ANYONE],408)
	Range(LastHeardBy(Myself),20)
	!CheckStatGT(Myself,99,RESISTACID)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	See([PC])
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		MoveToObject([PC])
END

IF
	Heard([ANYONE],404)
	Range(LastHeardBy(Myself),20)
	!General(Myself,UNDEAD)
	!Race(Myself,RAKSHASA)
	!Race(Myself,DEMONIC)
	OR(2)
		!CheckStatGT(Myself,80,RESISTMAGIC)
		!See(NearestEnemyOf(Myself))
	See([PC])
	!Range([PC],8)
THEN
	RESPONSE #100
		SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
		MoveToObject([PC])
END

IF
	!See(NearestEnemyOf(Myself))
	OR(8)
		Heard([ANYONE],404)
		Heard([ANYONE],405)
		Heard([ANYONE],406)
		Heard([ANYONE],407)
		Heard([ANYONE],408)
		Heard([ANYONE],409)
		Heard([ANYONE],410)
		Heard([ANYONE],411)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!Global("chasing","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("chasing","LOCALS",0)
		Continue()
END

IF
	ActionListEmpty()
	Global("inafight","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	Global("chasing","LOCALS",0)
	!Global("chasePC","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetimer","LOCALS",8)
		SetGlobal("chasing","LOCALS",1)
END

IF
	!See(NearestEnemyOf(Myself))
	GlobalTimerExpired("chasetimer","LOCALS")
	!Global("inafight","LOCALS",0)
	!Global("chasePC","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("inafight","LOCALS",0)
		SetGlobal("chasePC","LOCALS",0)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",1)
	!See(NearestEnemyOf(Myself))
	!Detect(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",2)
	!See(NearestEnemyOf(Myself))
	!Detect(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",3)
	!See(NearestEnemyOf(Myself))
	!Detect(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",4)
	!See(NearestEnemyOf(Myself))
	!Detect(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",5)
	!See(NearestEnemyOf(Myself))
	!Detect(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",6)
	!See(NearestEnemyOf(Myself))
	!Detect(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

IF
	StateCheck(Myself,STATE_CHARMED)
	See(NearestEnemyOf(Myself))
	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipRanged()
		Attack(NearestEnemyOf(Myself))
END

IF
	StateCheck(Myself,STATE_CHARMED)
	See(NearestEnemyOf(Myself))
	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Attack(NearestEnemyOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(NearestEnemyOf(Myself),ENEMY)
	!General(Myself,HUMANOID)
	OR(2)
		!General(Myself,GIANTHUMANOID)
		Race(Myself,GOLEM)
	OR(2)
		!General(Myself,UNDEAD)
		Race(Myself,ZOMBIE)
	!Race(Myself,LYCANTHROPE)
	!Race(Myself,DEMONIC)
	!Class(Myself,WOLF_VAMPIRIC)
	!Race(Myself,DRAGON)
	!Race(Myself,DOPPLEGANGER)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	See(LastTargetedBy(Myself))
	CheckStat(Myself,0,CLERIC_HALLOW)
	Global("validtarget","LOCALS",1)
	!CheckStat(LastTargetedBy(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",0)
		ClearActions(Myself)
END

IF
	See(LastTargetedBy(Myself))
	CheckStatLT(Myself,3,CLERIC_HALLOW)
	Global("validtarget","LOCALS",1)
	CheckStatGT(LastTargetedBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",0)
		ClearActions(Myself)
END

IF
	See(LastTargetedBy(Myself))
	CheckStat(Myself,3,CLERIC_HALLOW)
	Global("validtarget","LOCALS",1)
	CheckStatGT(LastTargetedBy(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",0)
		ClearActions(Myself)
END

IF
	See(LastTargetedBy(Myself))
	CheckStat(Myself,4,CLERIC_HALLOW)
	Global("validtarget","LOCALS",1)
	CheckStatGT(LastTargetedBy(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",0)
		ClearActions(Myself)
END

IF
	See(LastTargetedBy(Myself))
	!CheckStat(Myself,0,CLERIC_HALLOW)
	Global("validtarget","LOCALS",1)
	CheckStat(LastTargetedBy(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",0)
		ClearActions(Myself)
END

IF
	See([PC.0.0.MAGE])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.MAGE],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.MAGE])
END

IF
	See([PC.0.0.MAGE_THIEF])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.MAGE_THIEF],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.MAGE_THIEF])
END

IF
	See([PC.0.0.MAGE_ALL])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.MAGE_ALL],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.MAGE_ALL])
END

IF
	See([PC.0.0.THIEF])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.THIEF],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.THIEF])
END

IF
	See([PC.0.0.BARD])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.BARD],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.BARD])
END

IF
	See([PC.0.0.THIEF_ALL])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.THIEF_ALL],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.THIEF_ALL])
END

IF
	See([PC.0.0.CLERIC])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	OR(2)
		Range([PC.0.0.CLERIC],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC.0.0.CLERIC])
END

IF
	See([PC])
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	!CheckStatGT([PC],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	OR(2)
		Range([PC],4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack([PC])
END

IF
	See(SecondNearest([PC]))
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	OR(2)
		Range(SecondNearest([PC]),4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack(SecondNearest([PC]))
END

IF
	See(ThirdNearest([PC]))
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	OR(2)
		Range(ThirdNearest([PC]),4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack(ThirdNearest([PC]))
END

IF
	See(NearestEnemyOf(Myself))
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance(NearestEnemyOf(Myself),ENEMY)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",NearestEnemyOf(Myself))  // ??? ?????????????
	OR(2)
		Range(NearestEnemyOf(Myself),4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))  // ??? ?????????????
	OR(2)
		Range(SecondNearestEnemyOf(Myself),4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack(SecondNearestEnemyOf(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	StateCheck(Myself,STATE_INVISIBLE)
	Class(Myself,THIEF_ALL)
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))  // ??? ?????????????
	OR(2)
		Range(ThirdNearestEnemyOf(Myself),4)
		Global("backstabplan","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		Attack(ThirdNearestEnemyOf(Myself))
END

IF
	See([PC.0.0.MAGE])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE],20)
	Range([PC.0.0.MAGE],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE])
END

IF
	See([PC.0.0.MAGE_THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE_THIEF],20)
	Range([PC.0.0.MAGE_THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
	See([PC.0.0.MAGE_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE_ALL],20)
	Range([PC.0.0.MAGE_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
	See([PC.0.0.THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	!HPPercentGT([PC.0.0.THIEF],20)
	Range([PC.0.0.THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF])
END

IF
	See([PC.0.0.BARD])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	!HPPercentGT([PC.0.0.BARD],20)
	Range([PC.0.0.BARD],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.BARD])
END

IF
	See([PC.0.0.THIEF_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!HPPercentGT([PC.0.0.THIEF_ALL],20)
	Range([PC.0.0.THIEF_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
	See([PC.0.0.CLERIC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	!HPPercentGT([PC.0.0.CLERIC],20)
	Range([PC.0.0.CLERIC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.CLERIC])
END

IF
	See([PC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	!CheckStatGT([PC],0,STONESKINS)
	!HPPercentGT([PC],20)
	Range([PC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC])
END

IF
	See(SecondNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!HPPercentGT(SecondNearest([PC]),20)
	Range(SecondNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(SecondNearest([PC]))
END

IF
	See(ThirdNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!HPPercentGT(ThirdNearest([PC]),20)
	Range(ThirdNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(ThirdNearest([PC]))
END

IF
	See([PC.0.0.MAGE])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE],50)
	Range([PC.0.0.MAGE],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE])
END

IF
	See([PC.0.0.MAGE_THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE_THIEF],50)
	Range([PC.0.0.MAGE_THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
	See([PC.0.0.MAGE_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	!HPPercentGT([PC.0.0.MAGE_ALL],50)
	Range([PC.0.0.MAGE_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
	See([PC.0.0.THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	!HPPercentGT([PC.0.0.THIEF],50)
	Range([PC.0.0.THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF])
END

IF
	See([PC.0.0.BARD])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	!HPPercentGT([PC.0.0.BARD],50)
	Range([PC.0.0.BARD],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.BARD])
END

IF
	See([PC.0.0.THIEF_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	!HPPercentGT([PC.0.0.THIEF_ALL],50)
	Range([PC.0.0.THIEF_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
	See([PC.0.0.CLERIC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	!HPPercentGT([PC.0.0.CLERIC],50)
	Range([PC.0.0.CLERIC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.CLERIC])
END

IF
	See([PC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	!CheckStatGT([PC],0,STONESKINS)
	!HPPercentGT([PC],50)
	Range([PC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC])
END

IF
	See(SecondNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	!HPPercentGT(SecondNearest([PC]),50)
	Range(SecondNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(SecondNearest([PC]))
END

IF
	See(ThirdNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	!HPPercentGT(ThirdNearest([PC]),50)
	Range(ThirdNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(ThirdNearest([PC]))
END

IF
	See([PC.0.0.MAGE])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	Range([PC.0.0.MAGE],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE])
END

IF
	See([PC.0.0.MAGE_THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	Range([PC.0.0.MAGE_THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
	See([PC.0.0.MAGE_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	Range([PC.0.0.MAGE_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
	See([PC.0.0.THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	Range([PC.0.0.THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF])
END

IF
	See([PC.0.0.BARD])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	Range([PC.0.0.BARD],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.BARD])
END

IF
	See([PC.0.0.THIEF_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	Range([PC.0.0.THIEF_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
	See([PC.0.0.CLERIC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	Range([PC.0.0.CLERIC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.CLERIC])
END

IF
	See([PC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	!CheckStatGT([PC],0,STONESKINS)
	Range([PC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC])
END

IF
	See(SecondNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	Range(SecondNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(SecondNearest([PC]))
END

IF
	See(ThirdNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	Range(ThirdNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(ThirdNearest([PC]))
END

IF
	See([PC.0.0.MAGE])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	Range([PC.0.0.MAGE],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE])
END

IF
	See([PC.0.0.MAGE_THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	Range([PC.0.0.MAGE_THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
	See([PC.0.0.MAGE_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	Range([PC.0.0.MAGE_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
	See([PC.0.0.THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	Range([PC.0.0.THIEF],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF])
END

IF
	See([PC.0.0.BARD])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	Range([PC.0.0.BARD],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.BARD])
END

IF
	See([PC.0.0.THIEF_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	Range([PC.0.0.THIEF_ALL],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
	See([PC.0.0.CLERIC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	Range([PC.0.0.CLERIC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC.0.0.CLERIC])
END

IF
	See([PC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	Range([PC],4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound([PC])
END

IF
	See(SecondNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	Range(SecondNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(SecondNearest([PC]))
END

IF
	See(ThirdNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	Range(ThirdNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(ThirdNearest([PC]))
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(NearestEnemyOf(Myself),ENEMY)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",NearestEnemyOf(Myself))  // ??? ?????????????
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))  // ??? ?????????????
	Range(SecondNearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))  // ??? ?????????????
	Range(ThirdNearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		SetGlobal("validtarget","LOCALS",1)
		SetGlobal("melee","LOCALS",1)
		EquipMostDamagingMelee()
		AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
	HasItem("dw#move0",Myself)  // ???????? ????
THEN
	RESPONSE #100
		NoAction()
END

IF
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(NearestEnemyOf(Myself),ENEMY)
	!General(Myself,HUMANOID)
	OR(2)
		!General(Myself,GIANTHUMANOID)
		Race(Myself,GOLEM)
	OR(2)
		!General(Myself,UNDEAD)
		Race(Myself,ZOMBIE)
	!Race(Myself,LYCANTHROPE)
	!Race(Myself,DEMONIC)
	!Class(Myself,WOLF_VAMPIRIC)
	!Race(Myself,DRAGON)
	!Race(Myself,DOPPLEGANGER)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE])
	!HPPercentGT([PC.0.0.MAGE],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE])
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE_THIEF])
	!HPPercentGT([PC.0.0.MAGE_THIEF],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	!HPPercentGT([PC.0.0.MAGE_ALL],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE_ALL])
END

IF
	ActionListEmpty()
	See([PC.0.0.THIEF])
	!HPPercentGT([PC.0.0.THIEF],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.THIEF])
END

IF
	ActionListEmpty()
	See([PC.0.0.BARD])
	!HPPercentGT([PC.0.0.BARD],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.BARD])
END

IF
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	!HPPercentGT([PC.0.0.THIEF_ALL],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.THIEF_ALL])
END

IF
	ActionListEmpty()
	See([PC.0.0.CLERIC])
	!HPPercentGT([PC.0.0.CLERIC],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.CLERIC])
END

IF
	ActionListEmpty()
	See([PC])
	!HPPercentGT([PC],40)
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC])
END

IF
	ActionListEmpty()
	See(SecondNearest([PC]))
	!HPPercentGT(SecondNearest([PC]),40)
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(SecondNearest([PC]))
END

IF
	ActionListEmpty()
	See(ThirdNearest([PC]))
	!HPPercentGT(ThirdNearest([PC]),40)
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(ThirdNearest([PC]))
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE],ENEMY)
	!StateCheck([PC.0.0.MAGE],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE])
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE_THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
	ActionListEmpty()
	See([PC.0.0.MAGE_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.MAGE_ALL],ENEMY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.MAGE_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.MAGE_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.MAGE_ALL])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.MAGE_ALL])
END

IF
	ActionListEmpty()
	See([PC.0.0.THIEF])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF],ENEMY)
	!StateCheck([PC.0.0.THIEF],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.THIEF])
END

IF
	ActionListEmpty()
	See([PC.0.0.BARD])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.BARD],ENEMY)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.BARD])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.BARD])
END

IF
	ActionListEmpty()
	See([PC.0.0.THIEF_ALL])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.THIEF_ALL],ENEMY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.THIEF_ALL],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.THIEF_ALL],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.THIEF_ALL])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.THIEF_ALL])
END

IF
	ActionListEmpty()
	See([PC.0.0.CLERIC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC.0.0.CLERIC],ENEMY)
	!StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
	!CheckStatGT([PC.0.0.CLERIC],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC.0.0.CLERIC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC.0.0.CLERIC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC.0.0.CLERIC])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC.0.0.CLERIC])
END

IF
	ActionListEmpty()
	See([PC])
	Allegiance(Myself,ENEMY)
	!Allegiance([PC],ENEMY)
	!StateCheck([PC],STATE_DISABLED)
	!CheckStatGT([PC],0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat([PC],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat([PC],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat([PC],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat([PC],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat([PC],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",[PC])  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck([PC],STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT([PC],0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject([PC])
END

IF
	ActionListEmpty()
	See(SecondNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearest([PC]),ENEMY)
	!StateCheck(SecondNearest([PC]),STATE_DISABLED)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearest([PC]))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearest([PC]),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(SecondNearest([PC]))
END

IF
	ActionListEmpty()
	See(ThirdNearest([PC]))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearest([PC]),ENEMY)
	!StateCheck(ThirdNearest([PC]),STATE_DISABLED)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearest([PC]),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearest([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearest([PC]))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(ThirdNearest([PC]))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(NearestEnemyOf(Myself),ENEMY)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",NearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(SeventhNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(SeventhNearestEnemyOf(Myself),ENEMY)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(SeventhNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(SeventhNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(SeventhNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(SeventhNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(SeventhNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",SeventhNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SeventhNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(SeventhNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(SeventhNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(EighthNearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	!Allegiance(EighthNearestEnemyOf(Myself),ENEMY)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(EighthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(EighthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(EighthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(EighthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(EighthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",EighthNearestEnemyOf(Myself))  // ??? ?????????????
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!StateCheck(Myself,STATE_INVISIBLE)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(EighthNearestEnemyOf(Myself),0,STONESKINS)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	OR(3)
		!CheckStat(Myself,4,SCRIPTINGSTATE4)
		!Class(Myself,THIEF_ALL)
		!CheckStatGT(EighthNearestEnemyOf(Myself),0,STONESKINS)
THEN
	RESPONSE #100
		MoveToObject(EighthNearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(Player4)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player4,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player4,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player4,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player4,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player4,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player4)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player4)
END

IF
	ActionListEmpty()
	See(Player5)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player5,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player5,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player5,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player5,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player5,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player5)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player5)
END

IF
	ActionListEmpty()
	See(Player6)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player6,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player6,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player6,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player6,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player6,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player6)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player6)
END

IF
	ActionListEmpty()
	See(Player3)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player3,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player3,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player3,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player3,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player3,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player3)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player3)
END

IF
	ActionListEmpty()
	See(Player2)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player2,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player2,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player2,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player2,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player2,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player2)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player2)
END

IF
	ActionListEmpty()
	See(Player1)
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(Player1,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(Player1,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(Player1,1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(Player1,2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(Player1,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",Player1)  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(Player1)
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	Allegiance(Myself,ENEMY)
	OR(3)
		CheckStatGT(Myself,0,CLERIC_HALLOW)
		CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStat(Myself,0,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,2,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,3,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	OR(3)
		CheckStatGT(Myself,4,CLERIC_HALLOW)
		!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		GlobalTimerNotExpired("seedefences","LOCALS")
	!HasItem("MORSWORD",NearestEnemyOf(Myself))  // ??? ?????????????
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		SetGlobal("melee","LOCALS",1)
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!GlobalTimerNotExpired("setmeleetarget","LOCALS")
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	!Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	!Allegiance(Myself,ENEMY)
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
END

IF
	!Global("chasing","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("chasing","LOCALS",0)
		Continue()
END

IF
	ActionListEmpty()
	Global("inafight","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	Global("chasing","LOCALS",0)
	!Global("chasePC","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("chasetimer","LOCALS",8)
		SetGlobal("chasing","LOCALS",1)
END

IF
	!See(NearestEnemyOf(Myself))
	GlobalTimerExpired("chasetimer","LOCALS")
	!Global("inafight","LOCALS",0)
	!Global("chasePC","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("inafight","LOCALS",0)
		SetGlobal("chasePC","LOCALS",0)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",1)
	!See(NearestEnemyOf(Myself))
	!Detect(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",2)
	!See(NearestEnemyOf(Myself))
	!Detect(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",3)
	!See(NearestEnemyOf(Myself))
	!Detect(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",4)
	!See(NearestEnemyOf(Myself))
	!Detect(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",5)
	!See(NearestEnemyOf(Myself))
	!Detect(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	GlobalTimerNotExpired("chasetimer","LOCALS")
	Global("chasePC","LOCALS",6)
	!See(NearestEnemyOf(Myself))
	!Detect(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

IF
	Global("inafight","LOCALS",0)
	Global("helptarget","LOCALS",0)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
END

