IF
	Global("NWNw4002Entered","GLOBAL",1)
	OpenState("Carpet",FALSE)
THEN
	RESPONSE #100
		SetGlobal("NWNw4002Entered","GLOBAL",2)
		OpenDoor("Carpet")
		TriggerActivation("To4004",TRUE)
END

IF
	Global("TrapBlocked","MYAREA",0)
	PartyHasItem("Nwkey16")  // ?????? - ????
THEN
	RESPONSE #100
		SetGlobal("TrapBlocked","MYAREA",1)
		TriggerActivation("Close",FALSE)
		TriggerActivation("To4003",TRUE)
END

