IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,@14702)  // ??????? ??????, ????? ???????????? ???.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("NWGongUzed","MYAREA",0)
THEN
	RESPONSE #100
		PlaySound("Gongnw01")
		SetGlobal("NWGongUzed","MYAREA",1)
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	!Global("NWGongUzed","MYAREA",0)
THEN
	RESPONSE #100
		PlaySound("Gongnw01")
		SetGlobal("NWGongUzed","MYAREA",0)
END

