IF
	True()
THEN
	RESPONSE #100
		CutSceneId("NWTAMORA")  // ??????
		Wait(1)
		MoveToPoint([473.681])
		MoveToPoint([504.630])
		Face(14)
		DisplayStringHead(Myself,@103010)  // ??? ?? ???.
		Wait(2)
		FadeToColor([30.0],0)
		Wait(2)
		RestParty()
		Wait(3)
		FadeFromColor([30.0],0)
		MoveToPoint([646.765])
		Wait(2)
		Face(8)
		SetGlobalTimer("TamoraTimer","MYAREA",EIGHT_HOURS)
		Wait(1)
		EndCutSceneMode()
END

