IF
	OR(2)
		HitBy([PC],CRUSHING)
		AttackedBy([PC],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@88741)  // ?? ??????! ??? ???????? ????? ????!
		RunAwayFrom(LastAttackerOf(Myself),60)
		Continue()
END

IF
	CombatCounter(0)
	!Allegiance(Myself,NEUTRAL)
	!See([PC])
THEN
	RESPONSE #100
		ClearActions(Myself)
		ChangeEnemyAlly(Myself,NEUTRAL)
		Continue()
END

IF
	Delay(5)
	ActionListEmpty()
THEN
	RESPONSE #100
		RandomWalk()
END

